// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCdYl7316hqJpY7xtuzi_HbLcjJwYXig',
    appId: '1:449429397764:web:a2cf7efe5a27e4bf833051',
    messagingSenderId: '449429397764',
    projectId: 'geosense-3d013',
    authDomain: 'geosense-3d013.firebaseapp.com',
    storageBucket: 'geosense-3d013.appspot.com',
    measurementId: 'G-2W52MXBJTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPXNkTaQ3v_jw-bcgUu60nH6wCcfAJDRc',
    appId: '1:449429397764:android:41c338ecb41531d7833051',
    messagingSenderId: '449429397764',
    projectId: 'geosense-3d013',
    storageBucket: 'geosense-3d013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0lzggannShlhj09xsqRl4aaFRgbQMpTY',
    appId: '1:449429397764:ios:418c1328ad32a023833051',
    messagingSenderId: '449429397764',
    projectId: 'geosense-3d013',
    storageBucket: 'geosense-3d013.appspot.com',
    iosBundleId: 'com.example.smsDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0lzggannShlhj09xsqRl4aaFRgbQMpTY',
    appId: '1:449429397764:ios:418c1328ad32a023833051',
    messagingSenderId: '449429397764',
    projectId: 'geosense-3d013',
    storageBucket: 'geosense-3d013.appspot.com',
    iosBundleId: 'com.example.smsDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPCdYl7316hqJpY7xtuzi_HbLcjJwYXig',
    appId: '1:449429397764:web:ee22ff70180852f7833051',
    messagingSenderId: '449429397764',
    projectId: 'geosense-3d013',
    authDomain: 'geosense-3d013.firebaseapp.com',
    storageBucket: 'geosense-3d013.appspot.com',
    measurementId: 'G-E30N45Y24W',
  );
}
